database:
  host: 127.0.0.1
  port: 5432
  username: root
  password: password
  database: goload
cache:
  address: "127.0.0.1:6379"
  username: ""
  password: ""
mq:
  addresses:
    - 127.0.0.1:9092
  client_id: "goload"
auth:
  hash:
    cost: 10
  token:
    expires_in: 24h
grpc:
  address: "0.0.0.0:8083"
http:
  address: "0.0.0.0:8084"
download:
  mode: local
  download_directory: "./"
#   mode: s3
#   bucket: downloaded-files
#   address: "127.0.0.1:9000"
#   username: "ROOTUSER"
#   password: "CHANGEME123"